### PR TITLE
Producers

### PR DESCRIPTION
**Pull request by kreczko**
Was part of #4 and now separate from the fixes and selections.
In short, here I propose a simplified version of scribblers

### scribblers
```python
di_muon_mass = InvariantMass(
    'di_muon_mass',
    ['Muon_E[0]', 'Muon_Px[0]', 'Muon_Py[0]', 'Muon_Pz[0]'],
    ['Muon_E[1]', 'Muon_Px[1]', 'Muon_Py[1]', 'Muon_Pz[1]'],
)
modules.append(to_null_collector_pairs([di_muon_mass]))
```

### producers
```python
di_muon_mass = InvariantMass(
    'di_muon_mass',
    ['Muon_E[0]', 'Muon_Px[0]', 'Muon_Py[0]', 'Muon_Pz[0]'],
    ['Muon_E[1]', 'Muon_Px[1]', 'Muon_Py[1]', 'Muon_Pz[1]'],
)
modules.append(di_muon_mass.as_tuple())
```

At leading order it simply maps
`return to_null_collector_pairs([di_muon_mass])` &rarr; `di_muon_mass.as_tuple()`.

Deeper down, this PR adds the `BasicProducer`, which simplifies any other producer to only implement the `__init__` and `_value` (and `__repr__` if really different) functions. Other functions, `begin`, `event`, `_attach_to_event`, are already generalised.

Example plot from the invariant mass producer:
di_muon_mass

### CODE REVIEW

**Comment by TaiSakuma** [comment]
can you write more tests? Only `_extract_index()` has tests for few cases.

Can you add unit tests for `BasicProducer`, `NewFromFunction`, `Divide`, `TransverseMomentum`, `InvariantMass`?

Without tests, it is not clear from the PR how they work or even if they work.

**Comment by kreczko** [comment]
OK, this is now done as well. Thanks a lot for the feedback.

**Comment by kreczko** [comment]
This one is ready for merge as all.

**Comment by benkrikler** [comment]
Only just looking at this now.  What's the interplay and overlap between this edit and the [Scribbler repo](https://github.com/alphatwirl/scribblers)?

**Comment by kreczko** [comment]
Well, this PR mostly provides a new interface to scribblers with a few examples.
It is meant to reduce the amount of code you need to implement for every specialised scribbler (e.g. `TransverseMomentum`).

**Pull request merged**
